name: dowgan
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.8
  - pytorch=1.13.1
  - seaborn=0.12.2
  - scikit-learn=1.0.2
  - scipy=1.9.1
  - joblib=1.1.0
  - threadpoolctl=2.2.0
  - tensorflow = 2.11.0
  - keras = 2.11.0
  - tqdm = 4.65.0
  - plotly = 5.14.1
  