name: dowgan
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.8
  - pytorch=1.13.1
  - seaborn=0.12.2